version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: smart-ecommerce
    environment:
      POSTGRES_USER: spycon
      POSTGRES_PASSWORD: postgressPassword12345
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - ecommerce-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge